version: 2.1

jobs:
  build:
    description: Build application
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
        environment:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
      - run:
          name: "Setup Entity Framework"
          command: dotnet tool restore
      - run:
          name: "Update Database"
          command: dotnet ef database update --project=csye6225
      - run:
          name: "Run Tests"
          command: dotnet test
  pr_check:
    description: Pull Request Check
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
        environment:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
      - run:
          name: "Setup Entity Framework"
          command: dotnet tool restore
      - run:
          name: "Update Database"
          command: dotnet ef database update --project=csye6225
      - run:
          name: "Run Tests"
          command: dotnet test
workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  pr-check:
    jobs:
      - pr_check